server:
  port: 8888
  #port: 0
  contextPath: /

spring.application.name: configurator

spring.profiles.active: native

management.context-path: /actuator
management.security.enabled: false
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/projet/ecommerce/configurator/config



