server:
  port: 8888
  #port: 0
  contextPath: /
  shutdown: graceful

spring.application.name: configurator

spring.profiles.active: native

management.context-path: /actuator
management.security.enabled: false
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/projet/ecommerce/configurator/config


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  #    instance:
  #    preferIpAddress: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    health:
      probes:
        enabled: true


