server:
  port: 8888
  #port: 0
  contextPath: /
  shutdown: graceful

spring.application.name: configurator

spring.profiles.active: native

management.context-path: /actuator
management.security.enabled: false
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/projet/ecommerce/configurator/config


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  #    instance:
  #    preferIpAddress: true
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      connect-timeout: 30s
      read-timeout: 30s
      endpoint: ${ZIPKIN_URI:http://localhost:9411/api/v2/spans}

logging.pattern.level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


