
spring.application.name: order

server:
  port: 0
  contextPath: /

spring.profiles.active: h2
#spring.profiles.active: mysql

#eureka:
#    client:
#        serviceUrl:
#            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    instance:
#    preferIpAddress: true

# create and drop tables and sequences, loads import.sql
#spring.jpa.hibernate.ddl-auto: create-drop
#spring.jpa.hibernate.ddl-auto: none
spring.jpa.generate-ddl: false
spring.jpa.hibernate.ddl-auto: none

#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=system
#spring.datasource.password=password
#spring.datasource.driver-class-oracle.jdbc.driver.OracleDriver


liquibase.change-log: classpath:/db/changelog/db.changelog-master.xml

#endpoints.actuator.path: /admin
#management.context-path: /actuator
management.security.enabled: false

endpoints.sensitive: false

