

# Datasource

spring.datasource.url: jdbc:mysql://localhost/product
spring.datasource.username: productuser
spring.datasource.password: productpwd
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

liquibase.url: jdbc:mysql://localhost/product
liquibase.user: prodinstuser
liquibase.password: productpwd
liquibase.default-schema: product


