server:
  port: 19090
  contextPath: /

spring.application.name: reverseproxy


eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      routes:
      - id: baeldung_route
        uri: https://www.baeldung.com/
        predicates:
        - Path=/baeldung/
      - id: ui_route
        uri: lb://ui
        predicates:
          - Path=/ui/**
        filters:
          - StripPrefix=1
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

management.context-path: /actuator
management.security.enabled: false

management.endpoint.gateway.enabled: true




logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

#    root: DEBUG


