server:
  port: 19090
  contextPath: /

spring.application.name: reverseproxy


eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
    preferIpAddress: true


management.context-path: /actuator
management.security.enabled: false

