server:
  port: 19090
  contextPath: /
  shutdown: graceful

spring.application.name: reverseproxy


eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
    preferIpAddress: true

spring:
  cloud:
    gateway:
      routes:
      - id: baeldung_route
        uri: https://www.baeldung.com/
        predicates:
        - Path=/baeldung/
      - id: ui_route
        uri: lb://ui
        predicates:
          - Path=/ui/**
        filters:
          - StripPrefix=1
          - name: Retry
            args:
                retries: 1
                #statuses: '*'
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 50ms
                  factor: 2
                  basedOnPreviousValue: false
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
      metrics:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      probes:
        enabled: true

management.context-path: /actuator
management.security.enabled: false

management.endpoint.gateway.enabled: true





logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

#    root: DEBUG


