server.port: 9090

spring.application.name: reverseproxy


eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
    preferIpAddress: true
