
spring.application.name: ui

server:
  port: 0
  contextPath: /

#eureka:
#    client:
#        serviceUrl:
#            defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    instance:
#    preferIpAddress: true

#management.context-path: /actuator
#management.security.enabled: false

#endpoints.sensitive: false
