server:
  port: 8761
  contextPath: /
  shutdown: graceful

spring.application.name: discovery


management.context-path: /actuator
management.security.enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  #client:
  #  healthcheck:
  #    enabled: true
  #client.serviceUrl.defaultZone: http://localhost:8761/
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


management:
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      connect-timeout: 30s
      read-timeout: 30s
      endpoint: ${ZIPKIN_URI:http://localhost:9411/api/v2/spans}

logging.pattern.level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] [%kvp]'

